# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.runs/synth_1/.Xil/Vivado-14868-YH-LEARN829/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a100tftg256-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/head_file
    f:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/ip/clk_wiz_0
  } D:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      rt::read_verilog -include {
    F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/head_file
    f:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/ip/clk_wiz_0
  } {
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.runs/synth_1/.Xil/Vivado-14868-YH-LEARN829/realtime/clk_wiz_0_stub.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/E902_20191018.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/PAD_DIG_IO.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/PAD_OSC_IO.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/ahb_matrix_top.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/aou_top.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/apb0.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/apb0_sub_top.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/apb1.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/apb1_sub_top.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/clkgen.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/common.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/core_top.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/dmac.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/dummy.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/fpga_byte_spram.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/fpga_spram.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/gpio0.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/ls_sub_top.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/matrix.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/pdu_top.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/pwm.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/retu_top.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/rtc.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/sms.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/smu_top.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/tim.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/tim1.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/tim2.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/tim3.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/tim4.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/tim5.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/tim6.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/tim7.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/usi0.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/usi1.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/wdt.v
      F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.srcs/sources_1/imports/wujian_src/soc_file/wujian100_open_fpga_top.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.runs/synth_1/.Xil/Vivado-14868-YH-LEARN829/realtime/wujian100_open_top_synth.xdc
    rt::sdcChecksum
    set rt::top wujian100_open_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "F:/Nexysvideo_wujian100/perf_nexysvideo/project_perf/project_perf.runs/synth_1/.Xil/Vivado-14868-YH-LEARN829/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
